# Generated by Django 2.2.7 on 2019-12-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addressbook', '0001_initial'),
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationToVillage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressbook.Village')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationToSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressbook.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationToProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressbook.Province')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationToDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressbook.District')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationsToCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressbook.Cell')),
            ],
        ),
    ]
