# Generated by Django 2.2.8 on 2020-02-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communicationtodistrict',
            old_name='cell',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='communicationtoprovince',
            old_name='cell',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='communicationtosector',
            old_name='cell',
            new_name='sector',
        ),
        migrations.RenameField(
            model_name='communicationtovillage',
            old_name='cell',
            new_name='village',
        ),
    ]
